name: Build and Deploy

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
    - name: npm install
      uses: Jaid/action-npm-install@v1.2.4
      with:
        # NODE_ENV setting for installing execution (affects the amount of dependencies installed, but I would recommend keeping development in any case).
        nodeEnv: prod
        # Can be "npm", "yarn", "pnpm" or "auto". "auto" will determine the package manager by looking into the repo's files. This is very accurate, so you normally don't want to change this.
        packageManager: auto
        # If true and node_modules folder already exists, this action will be skipped assuming npm install is not required.
        skipIfNodeModulesExists: false

    - name: Build staw-utopia folder
      run: npm run build

    - name: deploy to site branch
      uses: s0/git-publish-subdir-action@develop
      env: 
        REPO: self # it is this repo not another on github or somewhere else
        BRANCH: site # the branch we deploy to
        FOLDER: staw-utopia
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # git auto populated variable with token for authenticated actions on the repo
        CLEAR_GLOBS_FILE: ".clear_globs_file" # prevent deletes in site branch based on glob file rules
